---
- name: Install Kubernetes prerequisites on Ubuntu
  hosts: all
  become: true
  vars:
    kubernetes_version: "1.24.0-00"

  tasks:
    - name: Update and install prerequisites
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - curl
        - gnupg
        - software-properties-common

    - name: Add Kubernetes apt key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes repository
      apt_repository:
        repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
        state: present

    - name: Update APT cache after adding Kubernetes repo
      apt:
        update_cache: yes

    - name: Install Kubernetes components (kubeadm, kubelet, kubectl)
      apt:
        name:
          - kubeadm={{ kubernetes_version }}
          - kubelet={{ kubernetes_version }}
          - kubectl={{ kubernetes_version }}
        state: present
      notify:
        - Enable and start kubelet service

    - name: Hold Kubernetes packages at current version
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present
        mark: hold

  handlers:
    - name: Enable and start kubelet service
      systemd:
        name: kubelet
        enabled: true
        state: started

- name: Initialize Kubernetes master
  hosts: master
  become: true
  tasks:
    - name: Initialize the Kubernetes cluster
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_init_output
      changed_when: "'This node has joined the cluster' not in kubeadm_init_output.stdout"

    - name: Create .kube directory for user
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy kubeconfig to user's kube directory
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ ansible_user }}/.kube/config"
        remote_src: yes
        owner: "{{ ansible_user }}"
        mode: '0644'

    - name: Deploy Flannel network
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      environment:
        KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"

    - name: Display join command for worker nodes
      debug:
        msg: "{{ kubeadm_init_output.stdout | regex_search('kubeadm join .+', '\\n') }}"

- name: Join worker nodes to the cluster
  hosts: workers
  become: true
  tasks:
    - name: Run kubeadm join
      command: "{{ hostvars['master']['kubeadm_init_output']['stdout'] | regex_search('kubeadm join .+', '\\n') }}"
      when: "'kubeadm join' in hostvars['master']['kubeadm_init_output']['stdout'"
