---
- name: Installer Docker et Docker Compose
  hosts: all
  become: true
  tasks:
    - name: Mettre à jour le cache APT
      apt:
        update_cache: yes

    - name: Installer les dépendances nécessaires
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Ajouter la clé GPG officielle de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Ajouter le dépôt Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present

    - name: Installer Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Activer et démarrer Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Ajouter l'utilisateur actuel au groupe docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Télécharger Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.0.0/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Vérifier l'installation de Docker et Docker Compose
      shell: |
        docker --version
        docker-compose --version
      register: docker_check
      ignore_errors: yes

    - name: Afficher les résultats de l'installation
      debug:
        var: docker_check.stdout
