---
- name: Installer Docker et Docker Compose
  hosts: all
  become: true
  tasks:
    - name: Mettre à jour le cache APT
      apt:
        update_cache: yes

    - name: Installer Docker (docker.io)
      apt:
        name: docker.io
        state: present

    - name: Activer et démarrer Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Ajouter l'utilisateur actuel au groupe docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Télécharger Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.0.0/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Vérifier l'installation de Docker et Docker Compose
      shell: |
        docker --version
        docker-compose --version
      register: docker_check
      ignore_errors: yes

    - name: Afficher les résultats de l'installation
      debug:
        var: docker_check.stdout
