---
- name: Install Docker and Docker Compose on Ubuntu via apt
  hosts: all
  become: true
  tasks:
    - name: Update and install prerequisites
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Update APT cache again
      apt:
        update_cache: yes

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Verify Docker and Docker Compose installation
      shell: |
        docker --version
        docker compose version
      register: docker_version
      changed_when: false
      ignore_errors: true

    - name: Display Docker and Docker Compose version
      debug:
        var: docker_version.stdout_lines
