- hosts: gitlab-server
  become: yes
  tasks:
    - name: Mettre à jour le système
      apt:
        update_cache: yes
        upgrade: dist

    - name: Installer les dépendances requises
      apt:
        name: 
          - curl
          - openssh-server
          - ca-certificates
          - tzdata
        state: present

    - name: Ajouter la clé GPG de GitLab
      apt_key:
        url: https://packages.gitlab.com/gitlab/gitlab-ee/gpgkey
        state: present

    - name: Ajouter le dépôt GitLab manuellement
      apt_repository:
        repo: "deb https://packages.gitlab.com/gitlab/gitlab-ee/ubuntu/ focal main"
        state: present

    - name: Mettre à jour le cache APT après l'ajout du dépôt
      apt:
        update_cache: yes

    - name: Installer GitLab
      apt:
        name: gitlab-ee
        state: present
      environment:
        EXTERNAL_URL: "http://gitlab.home.macloudconnect.com"  # Remplacez par votre propre domaine

    - name: Configurer GitLab
      command: gitlab-ctl reconfigure

    - name: Vérifier le statut de GitLab
      command: gitlab-ctl status
