---
- name: Install Kubernetes prerequisites on Ubuntu
  hosts: all
  become: true
  vars:
    kubernetes_version: "1.28.0-00"  # Remplace par la version souhaitée

  tasks:
    - name: Update and install prerequisites
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - curl
        - gnupg
        - software-properties-common

    - name: Create directory for Kubernetes keyring
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Kubernetes signing key
      ansible.builtin.command:
        cmd: "curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg"
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes APT repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
        state: present
        filename: 'kubernetes'

    - name: Update APT cache after adding Kubernetes repo
      apt:
        update_cache: yes

    - name: Install Kubernetes components (kubeadm, kubelet, kubectl)
      apt:
        name:
          - kubeadm={{ kubernetes_version }}
          - kubelet={{ kubernetes_version }}
          - kubectl={{ kubernetes_version }}
        state: present
      notify:
        - Enable and start kubelet service

    - name: Hold Kubernetes packages at current version
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: present
        mark: hold

  handlers:
    - name: Enable and start kubelet service
      systemd:
        name: kubelet
        enabled: true
        state: started
