- hosts: worker
  become: yes
  tasks:
    - name: ensure Kubernetes sysctl params file exists
      copy:
        dest: /etc/sysctl.d/99-kubernetes-cri.conf
        content: ''
        force: no

    - name: configure sysctl params for Kubernetes
      blockinfile:
        path: /etc/sysctl.d/99-kubernetes-cri.conf
        create: yes
        block: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1

    - name: apply sysctl params without reboot
      command: sysctl --system

    - name: configure crictl endpoint
      block:
        - name: create /etc/crictl directory
          file:
            path: /etc/crictl
            state: directory
            mode: '0755'

        - name: configure crictl to use containerd endpoint
          copy:
            content: "runtime-endpoint: unix:///run/containerd/containerd.sock\n"
            dest: /etc/crictl/crictl.yaml
            owner: root
            group: root
            mode: '0644'

    - name: join the cluster (use the token and control plane IP from the master)
      shell: kubeadm join <MASTER_IP>:6443 --token <TOKEN> --discovery-token-ca-cert-hash sha256:<HASH>
      args:
        creates: /var/lib/kubelet/kubeadm-flags.env
