---
- name: Deploy traefik v3
  hosts: all

  tasks:
    - name: Deploy traefik
      community.docker.docker_container:
        name: traefik
        image: "traefik:latest
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /run/docker.sock:/run/docker.sock
          - /etc/traefik:/etc/traefik
        restart_policy: unless-stopped
      become: true
      become_user: "{{ lookup('env', 'USER') }}"
